<?php
declare(strict_types=1);

require dirname(__DIR__) . '/_init.php';
adiwira_require_permission($pdo, 'plugin.study-interest.config.manage', false);

$versionId = filter_var($_GET['version_id'] ?? null, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]);
if ($versionId === false || $versionId === null) { http_response_code(404); echo study_interest_h(__('Assessment draft not found.')); return; }
$statement = $pdo->prepare('SELECT v.*,t.code AS test_code,t.title AS test_title,t.description AS test_description FROM study_interest_test_versions v JOIN study_interest_tests t ON t.id=v.test_id WHERE v.id=? LIMIT 1');
$statement->execute([(int)$versionId]);
$version = $statement->fetch(PDO::FETCH_ASSOC);
if (!is_array($version) || (string)$version['status'] !== 'draft') { http_response_code(404); echo study_interest_h(__('Only a draft assessment can be edited.')); return; }
$configuration = json_decode((string)$version['configuration_json'], true, 512, JSON_THROW_ON_ERROR);
if (!is_array($configuration) || !hash_equals((string)$version['configuration_hash'], hash('sha256', study_interest_configuration_json($configuration)))) throw new RuntimeException('Assessment configuration integrity check failed.');
$resultTextFields = [
    'score_name' => __('Score name'),
    'no_dominant_title' => __('Open-profile title'),
    'no_dominant_body' => __('Open-profile message'),
    'multidisciplinary' => __('Multidisciplinary message'),
    'biomedical_biotechnology_overlap' => __('Biomedical and biotechnology overlap'),
    'midwifery_overlap' => __('Midwifery overlap'),
    'professional_pathway' => __('Professional pathway heading'),
    'professional_pathway_body' => __('Professional pathway message'),
    'disclaimer' => __('Result disclaimer'),
];
?>
<div class="sie-admin sie-workspace-page">
  <?php study_interest_admin_nav('assessments'); ?>
  <a class="sie-back-link" href="<?= study_interest_h(study_interest_admin_url('assessments', ['version_id' => (int)$versionId])) ?>"><span aria-hidden="true">&larr;</span> <?= study_interest_h(__('Assessments')) ?></a>
  <header class="sie-admin-head"><div><span class="sie-admin-eyebrow"><?= study_interest_h((string)$version['version_code']) ?> &middot; <?= study_interest_h(__('Draft')) ?></span><h1 class="page-heading"><?= study_interest_h(__('Edit assessment configuration')) ?></h1><p><?= study_interest_h(__('Manage labels, section weights, dimensions, program mappings, and recommendation thresholds before publishing this draft.')) ?></p></div></header>
  <form class="sie-assessment-editor" method="post" action="<?= study_interest_h(study_interest_admin_action_url('assessments/save')) ?>">
    <input type="hidden" name="csrf_token" value="<?= study_interest_h(csrf_token()) ?>"><input type="hidden" name="version_id" value="<?= (int)$versionId ?>"><input type="hidden" name="expected_hash" value="<?= study_interest_h((string)$version['configuration_hash']) ?>">
    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Identity')) ?></span><h2><?= study_interest_h(__('Assessment information')) ?></h2></div></div><div class="sie-form-grid"><label><span><?= study_interest_h(__('Test code')) ?></span><input class="adam-input" readonly value="<?= study_interest_h((string)$version['test_code']) ?>"></label><label><span><?= study_interest_h(__('Version code')) ?></span><input class="adam-input" readonly value="<?= study_interest_h((string)$version['version_code']) ?>"></label><label class="is-wide"><span><?= study_interest_h(__('Test name')) ?></span><input class="adam-input" name="title" maxlength="255" required value="<?= study_interest_h((string)($configuration['title'] ?? $version['test_title'])) ?>"></label><label class="is-wide"><span><?= study_interest_h(__('Description')) ?></span><textarea class="adam-input" name="description" maxlength="2000"><?= study_interest_h((string)($configuration['description'] ?? $version['test_description'] ?? '')) ?></textarea></label></div></section>

    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Structure')) ?></span><h2><?= study_interest_h(__('Sections and contribution')) ?></h2></div><strong><?= count($configuration['sections'] ?? []) ?></strong></div><div class="sie-configuration-rows"><?php foreach ($configuration['sections'] ?? [] as $code => $section): ?><article><code><?= study_interest_h((string)$code) ?></code><label><span><?= study_interest_h(__('Section label')) ?></span><input class="adam-input" name="sections[<?= study_interest_h((string)$code) ?>][label]" maxlength="255" required value="<?= study_interest_h((string)$section['label']) ?>"></label><label><span><?= study_interest_h(__('Weight')) ?></span><input class="adam-input" type="number" name="sections[<?= study_interest_h((string)$code) ?>][weight]" min="0" max="1" step="0.00001" required value="<?= study_interest_h((string)$section['weight']) ?>"></label><span><?= (int)($section['question_count'] ?? 0) ?> <?= study_interest_h(__('questions')) ?></span></article><?php endforeach; ?></div></section>

    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Interest model')) ?></span><h2><?= study_interest_h(__('Dimensions')) ?></h2></div><strong><?= count($configuration['dimensions'] ?? []) ?></strong></div><div class="sie-dimension-editor"><?php foreach ($configuration['dimensions'] ?? [] as $code => $dimension): ?><article><code><?= study_interest_h((string)$code) ?></code><label><span><?= study_interest_h(__('Label')) ?></span><input class="adam-input" name="dimensions[<?= study_interest_h((string)$code) ?>][label]" maxlength="255" required value="<?= study_interest_h((string)$dimension['label']) ?>"></label><label><span><?= study_interest_h(__('Description')) ?></span><textarea class="adam-input" name="dimensions[<?= study_interest_h((string)$code) ?>][description]" maxlength="1000"><?= study_interest_h((string)($dimension['description'] ?? '')) ?></textarea></label></article><?php endforeach; ?></div></section>

    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Recommendation model')) ?></span><h2><?= study_interest_h(__('Programs and dimension weights')) ?></h2></div><strong><?= count($configuration['programs'] ?? []) ?></strong></div><div class="sie-program-editor"><?php foreach ($configuration['programs'] ?? [] as $programCode => $program): ?><article><div class="sie-program-editor__head"><code><?= study_interest_h((string)$programCode) ?></code><label><span><?= study_interest_h(__('Program label')) ?></span><input class="adam-input" name="programs[<?= study_interest_h((string)$programCode) ?>][label]" maxlength="255" required value="<?= study_interest_h((string)$program['label']) ?>"></label><label><span><?= study_interest_h(__('Path type')) ?></span><select class="adam-input" name="programs[<?= study_interest_h((string)$programCode) ?>][recommendation_type]"><option value="DIRECT_ENTRY" <?= (string)$program['recommendation_type'] === 'DIRECT_ENTRY' ? 'selected' : '' ?>>Direct entry</option><option value="PROFESSIONAL_PATHWAY" <?= (string)$program['recommendation_type'] === 'PROFESSIONAL_PATHWAY' ? 'selected' : '' ?>>Professional pathway</option></select></label></div><div class="sie-program-weight-grid"><?php foreach ($configuration['dimensions'] as $dimensionCode => $dimension): ?><label><span><b><?= study_interest_h((string)$dimensionCode) ?></b><?= study_interest_h((string)$dimension['label']) ?></span><input class="adam-input" type="number" min="0" max="1" step="0.00001" required name="programs[<?= study_interest_h((string)$programCode) ?>][weights][<?= study_interest_h((string)$dimensionCode) ?>]" value="<?= study_interest_h((string)($program['weights'][$dimensionCode] ?? 0)) ?>"></label><?php endforeach; ?></div></article><?php endforeach; ?></div></section>

    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Decision rules')) ?></span><h2><?= study_interest_h(__('Recommendation thresholds')) ?></h2></div></div><div class="sie-threshold-grid"><label><span><?= study_interest_h(__('Strong recommendation minimum')) ?></span><input class="adam-input" type="number" min="0" max="100" step="0.01" name="thresholds[direct_recommendation_minimum]" value="<?= study_interest_h((string)($configuration['thresholds']['direct_recommendation_minimum'] ?? 55)) ?>" required><small><?= study_interest_h(__('Leading direction is always shown; this threshold only marks stronger matches.')) ?></small></label><label><span><?= study_interest_h(__('Directions shown')) ?></span><input class="adam-input" type="number" min="1" max="8" step="1" name="thresholds[direct_recommendation_limit]" value="<?= (int)($configuration['thresholds']['direct_recommendation_limit'] ?? 3) ?>" required></label><label><span><?= study_interest_h(__('Professional pathway minimum')) ?></span><input class="adam-input" type="number" min="0" max="100" step="0.01" name="thresholds[professional_pathway_minimum]" value="<?= study_interest_h((string)($configuration['thresholds']['professional_pathway_minimum'] ?? 70)) ?>" required></label></div></section>
    <section class="sie-editor-panel"><div class="sie-panel-title"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Result content')) ?></span><h2><?= study_interest_h(__('Participant-facing result messages')) ?></h2></div></div><p class="sie-panel-note"><?= study_interest_h(__('These messages are frozen into this version when it is published. Access, masking, and hidden-page messages remain under Result page.')) ?></p><div class="sie-form-grid"><?php foreach ($resultTextFields as $key => $label): ?><label class="<?= in_array($key, ['score_name', 'no_dominant_title', 'professional_pathway'], true) ? '' : 'is-wide' ?>"><span><?= study_interest_h($label) ?></span><?php if (in_array($key, ['score_name', 'no_dominant_title', 'professional_pathway'], true)): ?><input class="adam-input" name="result_text[<?= study_interest_h($key) ?>]" maxlength="255" required value="<?= study_interest_h((string)($configuration['result_text'][$key] ?? '')) ?>"><?php else: ?><textarea class="adam-input" name="result_text[<?= study_interest_h($key) ?>]" maxlength="2000" required><?= study_interest_h((string)($configuration['result_text'][$key] ?? '')) ?></textarea><?php endif; ?></label><?php endforeach; ?></div></section>
    <div class="sie-sticky-save"><div><strong><?= study_interest_h(__('Draft configuration')) ?></strong><span><?= study_interest_h(__('Saving recalculates the configuration fingerprint and publication checks.')) ?></span></div><button class="adam-button" type="submit"><?= study_interest_h(__('Save assessment')) ?></button></div>
  </form>
  <section class="sie-editor-panel sie-danger-zone"><span class="sie-admin-eyebrow"><?= study_interest_h(__('Danger zone')) ?></span><h2><?= study_interest_h(__('Delete this draft')) ?></h2><p class="sie-panel-note"><?= study_interest_h(__('Only an unpublished draft without participant sessions can be deleted. Published and retired versions remain immutable.')) ?></p><form method="post" action="<?= study_interest_h(study_interest_admin_action_url('assessments/delete')) ?>" data-sie-confirm data-sie-confirm-title="<?= study_interest_h(__('Delete this assessment draft?')) ?>" data-sie-confirm-message="<?= study_interest_h(__('The draft configuration, questions, answer options, and scoring model will be permanently removed.')) ?>" data-sie-confirm-text="<?= study_interest_h(__('Delete draft')) ?>"><input type="hidden" name="csrf_token" value="<?= study_interest_h(csrf_token()) ?>"><input type="hidden" name="version_id" value="<?= (int)$versionId ?>"><input type="hidden" name="expected_hash" value="<?= study_interest_h((string)$version['configuration_hash']) ?>"><label><span><?= study_interest_h(__('Deletion reason')) ?></span><textarea class="adam-input" name="reason" minlength="5" maxlength="500" required></textarea></label><button class="adam-button secondary sie-danger-button" type="submit"><?= study_interest_h(__('Delete assessment draft')) ?></button></form></section>
</div>
