<?php
declare(strict_types=1);

$likertLabels = [
    1 => 'Sangat Tidak Sesuai',
    2 => 'Tidak Sesuai',
    3 => 'Netral/Ragu-ragu',
    4 => 'Sesuai',
    5 => 'Sangat Sesuai',
];

$dimensionLikert = static function (string $dimension, bool $reverse = false) use ($likertLabels): array {
    $options = [];
    foreach ($likertLabels as $value => $label) {
        $options[] = [
            'code' => (string)$value,
            'value' => $value,
            'label' => $label,
            'scores' => [$dimension => $reverse ? 6 - $value : $value],
        ];
    }
    return $options;
};

$weightedLikert = static function (array $shares) use ($likertLabels): array {
    $options = [];
    foreach ($likertLabels as $value => $label) {
        $normalized = ($value - 1) * 25;
        $scores = [];
        foreach ($shares as $dimension => $share) {
            $scores[$dimension] = $normalized * $share;
        }
        $options[] = [
            'code' => (string)$value,
            'value' => $value,
            'label' => $label,
            'normalized_value' => $normalized,
            'scores' => $scores,
        ];
    }
    return $options;
};

return [
    'code' => 'study-interest',
    'title' => 'Study Interest Explorer',
    'description' => 'A flexible exploration of study interests and preferred activities.',
    'locale' => 'id',
    'version' => 'baseline-1.0',
    'algorithm_version' => 'baseline-1.0',
    'status' => 'baseline',
    'dimensions' => [
        'SCI' => ['label' => 'Scientific Exploration', 'description' => 'Rasa ingin tahu ilmiah, penelitian, dan eksperimen.'],
        'HHC' => ['label' => 'Human & Health Care', 'description' => 'Minat pada manusia, kesehatan, dan pelayanan.'],
        'TEC' => ['label' => 'Technology & Data', 'description' => 'Teknologi, data, dan sistem digital.'],
        'ANA' => ['label' => 'Analytical Thinking', 'description' => 'Pola, sebab-akibat, dan pemecahan masalah.'],
        'COM' => ['label' => 'Communication & Social Influence', 'description' => 'Komunikasi, presentasi, media, dan pengaruh sosial.'],
        'BUS' => ['label' => 'Business & Leadership', 'description' => 'Bisnis, organisasi, kepemimpinan, dan kewirausahaan.'],
        'REG' => ['label' => 'Regulation & Justice', 'description' => 'Hukum, aturan, kebijakan, hak, dan keadilan.'],
        'PRA' => ['label' => 'Practical & Clinical Orientation', 'description' => 'Aktivitas langsung, prosedur, dan praktik klinis atau terapan.'],
    ],
    'sections' => [
        'A' => ['label' => 'Interest Statements', 'weight' => 0.45, 'question_count' => 24, 'display_order' => 1],
        'B' => ['label' => 'Situational Choice', 'weight' => 0.30, 'question_count' => 10, 'display_order' => 2],
        'C' => ['label' => 'Learning & Work Preference', 'weight' => 0.15, 'question_count' => 6, 'display_order' => 3],
        'D' => ['label' => 'Future Orientation', 'weight' => 0.10, 'question_count' => 5, 'display_order' => 4],
    ],
    'questions' => [
        [
            'code' => 'Q1',
            'section' => 'A',
            'prompt' => 'Saya sering penasaran mengapa suatu penyakit atau kondisi tertentu bisa menyebabkan perubahan pada tubuh manusia.',
            'type' => 'likert',
            'dimension' => 'SCI',
            'is_reverse' => false,
            'options' => $dimensionLikert('SCI'),
        ],
        [
            'code' => 'Q2',
            'section' => 'A',
            'prompt' => 'Saya menikmati mencari penjelasan ilmiah mengenai sesuatu, bukan hanya mengetahui hasil akhirnya.',
            'type' => 'likert',
            'dimension' => 'SCI',
            'is_reverse' => false,
            'options' => $dimensionLikert('SCI'),
        ],
        [
            'code' => 'Q3',
            'section' => 'A',
            'prompt' => 'Jika sudah mengetahui jawabannya, saya biasanya tidak terlalu tertarik mencari tahu bagaimana proses di baliknya.',
            'type' => 'likert',
            'dimension' => 'SCI',
            'is_reverse' => true,
            'options' => $dimensionLikert('SCI', true),
        ],
        [
            'code' => 'Q4',
            'section' => 'A',
            'prompt' => 'Saya tertarik mempelajari kesehatan manusia, tubuh, kehamilan, penyakit, atau proses biologis manusia.',
            'type' => 'likert',
            'dimension' => 'HHC',
            'is_reverse' => false,
            'options' => $dimensionLikert('HHC'),
        ],
        [
            'code' => 'Q5',
            'section' => 'A',
            'prompt' => 'Saya merasa puas ketika dapat membantu seseorang memahami masalah yang berkaitan dengan kesehatan atau kesejahteraannya.',
            'type' => 'likert',
            'dimension' => 'HHC',
            'is_reverse' => false,
            'options' => $dimensionLikert('HHC'),
        ],
        [
            'code' => 'Q6',
            'section' => 'A',
            'prompt' => 'Saya lebih menyukai kegiatan yang sama sekali tidak berhubungan dengan kondisi atau kebutuhan manusia.',
            'type' => 'likert',
            'dimension' => 'HHC',
            'is_reverse' => true,
            'options' => $dimensionLikert('HHC', true),
        ],
        [
            'code' => 'Q7',
            'section' => 'A',
            'prompt' => 'Saya menikmati menggunakan aplikasi, teknologi, data, atau sistem digital untuk menyelesaikan masalah.',
            'type' => 'likert',
            'dimension' => 'TEC',
            'is_reverse' => false,
            'options' => $dimensionLikert('TEC'),
        ],
        [
            'code' => 'Q8',
            'section' => 'A',
            'prompt' => 'Saya penasaran bagaimana AI, data, atau teknologi dapat digunakan untuk membuat suatu pekerjaan menjadi lebih baik.',
            'type' => 'likert',
            'dimension' => 'TEC',
            'is_reverse' => false,
            'options' => $dimensionLikert('TEC'),
        ],
        [
            'code' => 'Q9',
            'section' => 'A',
            'prompt' => 'Menurut saya, penggunaan data dan teknologi biasanya justru membuat pekerjaan menjadi lebih rumit.',
            'type' => 'likert',
            'dimension' => 'TEC',
            'is_reverse' => true,
            'options' => $dimensionLikert('TEC', true),
        ],
        [
            'code' => 'Q10',
            'section' => 'A',
            'prompt' => 'Saya menikmati persoalan yang membutuhkan beberapa petunjuk sebelum menemukan jawabannya.',
            'type' => 'likert',
            'dimension' => 'ANA',
            'is_reverse' => false,
            'options' => $dimensionLikert('ANA'),
        ],
        [
            'code' => 'Q11',
            'section' => 'A',
            'prompt' => 'Sebelum mengambil keputusan, saya suka membandingkan fakta atau bukti yang tersedia.',
            'type' => 'likert',
            'dimension' => 'ANA',
            'is_reverse' => false,
            'options' => $dimensionLikert('ANA'),
        ],
        [
            'code' => 'Q12',
            'section' => 'A',
            'prompt' => 'Saya lebih suka mengambil kesimpulan dengan cepat daripada mencari penyebab sebuah masalah secara mendalam.',
            'type' => 'likert',
            'dimension' => 'ANA',
            'is_reverse' => true,
            'options' => $dimensionLikert('ANA', true),
        ],
        [
            'code' => 'Q13',
            'section' => 'A',
            'prompt' => 'Saya menikmati menjelaskan suatu ide kepada orang lain.',
            'type' => 'likert',
            'dimension' => 'COM',
            'is_reverse' => false,
            'options' => $dimensionLikert('COM'),
        ],
        [
            'code' => 'Q14',
            'section' => 'A',
            'prompt' => 'Presentasi, membuat konten, berdiskusi, atau berbicara di depan orang lain merupakan kegiatan yang menarik bagi saya.',
            'type' => 'likert',
            'dimension' => 'COM',
            'is_reverse' => false,
            'options' => $dimensionLikert('COM'),
        ],
        [
            'code' => 'Q15',
            'section' => 'A',
            'prompt' => 'Walaupun memahami suatu topik, saya biasanya tidak tertarik menyampaikan ide tersebut kepada orang lain.',
            'type' => 'likert',
            'dimension' => 'COM',
            'is_reverse' => true,
            'options' => $dimensionLikert('COM', true),
        ],
        [
            'code' => 'Q16',
            'section' => 'A',
            'prompt' => 'Saya menikmati merencanakan suatu kegiatan dan memikirkan bagaimana orang-orang dapat bekerja bersama untuk mencapai target.',
            'type' => 'likert',
            'dimension' => 'BUS',
            'is_reverse' => false,
            'options' => $dimensionLikert('BUS'),
        ],
        [
            'code' => 'Q17',
            'section' => 'A',
            'prompt' => 'Ketika melihat sebuah ide atau produk, saya sering memikirkan bagaimana ide tersebut dapat dikembangkan menjadi sesuatu yang bernilai.',
            'type' => 'likert',
            'dimension' => 'BUS',
            'is_reverse' => false,
            'options' => $dimensionLikert('BUS'),
        ],
        [
            'code' => 'Q18',
            'section' => 'A',
            'prompt' => 'Saya lebih nyaman selalu mengikuti instruksi daripada harus menentukan strategi atau mengambil keputusan.',
            'type' => 'likert',
            'dimension' => 'BUS',
            'is_reverse' => true,
            'options' => $dimensionLikert('BUS', true),
        ],
        [
            'code' => 'Q19',
            'section' => 'A',
            'prompt' => 'Saya tertarik mengetahui mengapa suatu aturan dibuat dan apakah aturan tersebut sudah adil.',
            'type' => 'likert',
            'dimension' => 'REG',
            'is_reverse' => false,
            'options' => $dimensionLikert('REG'),
        ],
        [
            'code' => 'Q20',
            'section' => 'A',
            'prompt' => 'Saya menikmati diskusi mengenai hak, kewajiban, aturan, keadilan, atau perbedaan pendapat.',
            'type' => 'likert',
            'dimension' => 'REG',
            'is_reverse' => false,
            'options' => $dimensionLikert('REG'),
        ],
        [
            'code' => 'Q21',
            'section' => 'A',
            'prompt' => 'Pembahasan mengenai hukum, aturan, atau kebijakan biasanya membuat saya cepat kehilangan minat.',
            'type' => 'likert',
            'dimension' => 'REG',
            'is_reverse' => true,
            'options' => $dimensionLikert('REG', true),
        ],
        [
            'code' => 'Q22',
            'section' => 'A',
            'prompt' => 'Saya menikmati kegiatan yang membuat saya dapat mencoba sesuatu secara langsung, bukan hanya membaca teorinya.',
            'type' => 'likert',
            'dimension' => 'PRA',
            'is_reverse' => false,
            'options' => $dimensionLikert('PRA'),
        ],
        [
            'code' => 'Q23',
            'section' => 'A',
            'prompt' => 'Saya lebih mudah memahami sesuatu ketika dapat mempraktikkannya sendiri.',
            'type' => 'likert',
            'dimension' => 'PRA',
            'is_reverse' => false,
            'options' => $dimensionLikert('PRA'),
        ],
        [
            'code' => 'Q24',
            'section' => 'A',
            'prompt' => 'Saya lebih memilih pembahasan teori dibanding melakukan aktivitas atau prosedur secara langsung.',
            'type' => 'likert',
            'dimension' => 'PRA',
            'is_reverse' => true,
            'options' => $dimensionLikert('PRA', true),
        ],
        [
            'code' => 'Q25',
            'section' => 'B',
            'title' => 'Pameran Sains Sekolah',
            'prompt' => 'Sekolahmu mengadakan pameran inovasi. Tim kamu bebas menentukan proyek. Kamu lebih tertarik untuk:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Meneliti perubahan pada sel atau fenomena biologis.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Membuat aplikasi atau dashboard untuk mengolah data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Membuat kegiatan edukasi mengenai kesehatan.', 'scores' => ['HHC' => 3, 'COM' => 1]],
                ['code' => 'D', 'label' => 'Membuat strategi bisnis untuk menjual hasil inovasi.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Mengkaji aturan dan etika yang berkaitan dengan inovasi tersebut.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q26',
            'section' => 'B',
            'title' => 'Informasi Kesehatan yang Salah',
            'prompt' => 'Di media sosial beredar informasi kesehatan yang meragukan. Kamu paling tertarik untuk:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Mencari penelitian ilmiah yang menjelaskan masalah tersebut.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Menganalisis data penyebaran informasinya.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Membuat konten yang menjelaskan informasi yang benar kepada masyarakat.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'D', 'label' => 'Mengorganisasi orang dan sumber daya untuk membuat program edukasi.', 'scores' => ['BUS' => 3, 'HHC' => 1]],
                ['code' => 'E', 'label' => 'Mengkaji aturan dan tanggung jawab terhadap penyebaran informasi tersebut.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q27',
            'section' => 'B',
            'title' => 'Membuat Produk Baru',
            'prompt' => 'Tim kamu diminta membuat sebuah produk baru. Bagian yang paling ingin kamu kerjakan adalah:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Membuat dan menguji prototipe secara langsung.', 'scores' => ['PRA' => 3, 'SCI' => 1]],
                ['code' => 'B', 'label' => 'Membuat sistem digital untuk mengumpulkan dan menganalisis data produk.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Mewawancarai pengguna dan mempresentasikan konsep produk.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'D', 'label' => 'Menentukan target pasar, harga, dan model bisnis.', 'scores' => ['BUS' => 3, 'ANA' => 1]],
                ['code' => 'E', 'label' => 'Memastikan produk memenuhi aturan dan persyaratan yang berlaku.', 'scores' => ['REG' => 3, 'PRA' => 1]],
            ],
        ],
        [
            'code' => 'Q28',
            'section' => 'B',
            'title' => 'Program Pengabdian Masyarakat',
            'prompt' => 'Sekolah mengadakan kegiatan di sebuah desa. Kamu lebih ingin:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Melakukan aktivitas pelayanan kesehatan sederhana di bawah pengawasan tenaga profesional.', 'scores' => ['PRA' => 3, 'HHC' => 1]],
                ['code' => 'B', 'label' => 'Mengumpulkan sampel dan mengamati fenomena biologis.', 'scores' => ['SCI' => 3, 'PRA' => 1]],
                ['code' => 'C', 'label' => 'Membuat sistem digital untuk pencatatan data kegiatan.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'D', 'label' => 'Menjadi bagian dari tim kampanye dan edukasi masyarakat.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'E', 'label' => 'Mengatur logistik, jadwal dan pembagian tugas tim.', 'scores' => ['BUS' => 3, 'PRA' => 1]],
            ],
        ],
        [
            'code' => 'Q29',
            'section' => 'B',
            'title' => 'Perselisihan di Sekolah',
            'prompt' => 'Dua kelompok siswa mengalami perselisihan. Kamu lebih tertarik untuk:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Mempelajari aturan sekolah dan bukti dari kedua pihak.', 'scores' => ['REG' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Menjadi mediator agar kedua pihak dapat berkomunikasi.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'C', 'label' => 'Menelusuri fakta dan mencari akar penyebab masalah.', 'scores' => ['ANA' => 3, 'REG' => 1]],
                ['code' => 'D', 'label' => 'Menyusun rencana penyelesaian dan mengorganisasi pihak terkait.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Membuat sistem pencatatan kejadian agar informasi lebih terstruktur.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q30',
            'section' => 'B',
            'title' => 'Kesempatan Magang',
            'prompt' => 'Jika memperoleh kesempatan mencoba magang selama satu minggu, tempat yang paling menarik bagimu adalah:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Laboratorium penelitian.', 'scores' => ['SCI' => 3, 'PRA' => 1]],
                ['code' => 'B', 'label' => 'Klinik atau pelayanan kesehatan.', 'scores' => ['HHC' => 3, 'PRA' => 1]],
                ['code' => 'C', 'label' => 'Perusahaan teknologi atau data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'D', 'label' => 'Media, marketing atau creative agency.', 'scores' => ['COM' => 3, 'BUS' => 1]],
                ['code' => 'E', 'label' => 'Kantor hukum atau bagian compliance perusahaan.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q31',
            'section' => 'B',
            'title' => 'Proyek Kelompok Tidak Berjalan Sesuai Rencana',
            'prompt' => 'Hal pertama yang paling ingin kamu lakukan adalah:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Menguji kembali dugaan atau hipotesis awal.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Memeriksa data atau sistem yang digunakan.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Bertanya kepada anggota tim dan pengguna untuk mengetahui masalahnya.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'D', 'label' => 'Menyusun ulang strategi, sumber daya, dan pembagian tugas.', 'scores' => ['BUS' => 3, 'ANA' => 1]],
                ['code' => 'E', 'label' => 'Memeriksa apakah prosedur yang digunakan sudah sesuai.', 'scores' => ['REG' => 3, 'PRA' => 1]],
            ],
        ],
        [
            'code' => 'Q32',
            'section' => 'B',
            'title' => 'Berita yang Paling Menarik',
            'prompt' => 'Manakah berita yang kemungkinan paling membuatmu ingin membaca sampai selesai?',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Penemuan baru mengenai sel, tubuh manusia, atau penyakit.', 'scores' => ['SCI' => 3, 'HHC' => 1]],
                ['code' => 'B', 'label' => 'Perkembangan terbaru AI dan teknologi data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Kampanye sosial atau media yang menjadi perhatian masyarakat.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'D', 'label' => 'Kisah perkembangan sebuah startup atau bisnis.', 'scores' => ['BUS' => 3, 'ANA' => 1]],
                ['code' => 'E', 'label' => 'Keputusan pengadilan atau perubahan regulasi penting.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q33',
            'section' => 'B',
            'title' => 'Organisasi Sekolah',
            'prompt' => 'Jika harus memilih satu divisi, kamu akan memilih:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Divisi penelitian atau akademik.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Divisi teknologi dan data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Divisi sosial dan pelayanan masyarakat.', 'scores' => ['HHC' => 3, 'COM' => 1]],
                ['code' => 'D', 'label' => 'Divisi entrepreneurship atau kepemimpinan organisasi.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Divisi debat, advokasi atau kajian kebijakan.', 'scores' => ['REG' => 3, 'COM' => 1]],
            ],
        ],
        [
            'code' => 'Q34',
            'section' => 'B',
            'title' => 'Masalah Mendesak',
            'prompt' => 'Ketika menghadapi masalah yang harus segera diselesaikan, kamu lebih nyaman:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Melakukan prosedur praktis yang langkahnya jelas.', 'scores' => ['PRA' => 3, 'HHC' => 1]],
                ['code' => 'B', 'label' => 'Mencari akar penyebab masalah.', 'scores' => ['ANA' => 3, 'SCI' => 1]],
                ['code' => 'C', 'label' => 'Mengkoordinasikan orang dan sumber daya.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'D', 'label' => 'Menjelaskan situasi kepada orang lain.', 'scores' => ['COM' => 3, 'HHC' => 1]],
                ['code' => 'E', 'label' => 'Memastikan keputusan tidak melanggar aturan atau menimbulkan risiko.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q35',
            'section' => 'C',
            'prompt' => 'Saya akan menikmati kegiatan kuliah yang banyak menggunakan laboratorium, eksperimen, atau praktik ilmiah.',
            'type' => 'likert',
            'dimension_shares' => ['SCI' => 0.60, 'PRA' => 0.40],
            'options' => $weightedLikert(['SCI' => 0.60, 'PRA' => 0.40]),
        ],
        [
            'code' => 'Q36',
            'section' => 'C',
            'prompt' => 'Saya menikmati aktivitas yang membuat saya berinteraksi langsung dengan orang dan memahami kebutuhan mereka.',
            'type' => 'likert',
            'dimension_shares' => ['HHC' => 0.70, 'COM' => 0.30],
            'options' => $weightedLikert(['HHC' => 0.70, 'COM' => 0.30]),
        ],
        [
            'code' => 'Q37',
            'section' => 'C',
            'prompt' => 'Saya menikmati pekerjaan yang menggunakan angka, data, teknologi digital atau software.',
            'type' => 'likert',
            'dimension_shares' => ['TEC' => 0.70, 'ANA' => 0.30],
            'options' => $weightedLikert(['TEC' => 0.70, 'ANA' => 0.30]),
        ],
        [
            'code' => 'Q38',
            'section' => 'C',
            'prompt' => 'Saya menikmati diskusi, presentasi, debat dan mempertahankan suatu pendapat.',
            'type' => 'likert',
            'dimension_shares' => ['COM' => 0.60, 'REG' => 0.40],
            'options' => $weightedLikert(['COM' => 0.60, 'REG' => 0.40]),
        ],
        [
            'code' => 'Q39',
            'section' => 'C',
            'prompt' => 'Saya tertarik memimpin tim, menentukan target, atau mengubah sebuah ide menjadi proyek atau usaha.',
            'type' => 'likert',
            'dimension_shares' => ['BUS' => 0.70, 'ANA' => 0.30],
            'options' => $weightedLikert(['BUS' => 0.70, 'ANA' => 0.30]),
        ],
        [
            'code' => 'Q40',
            'section' => 'C',
            'prompt' => 'Saya menikmati pekerjaan yang membutuhkan prosedur praktis, ketelitian dan urutan kerja yang jelas.',
            'type' => 'likert',
            'dimension_shares' => ['PRA' => 0.60, 'ANA' => 0.40],
            'options' => $weightedLikert(['PRA' => 0.60, 'ANA' => 0.40]),
        ],
        [
            'code' => 'Q41',
            'section' => 'D',
            'title' => 'Dampak yang Ingin Kamu Berikan',
            'prompt' => 'Di masa depan, pencapaian mana yang paling membuatmu merasa puas?',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Menemukan atau menjelaskan sesuatu yang sebelumnya belum dipahami secara ilmiah.', 'scores' => ['SCI' => 3, 'HHC' => 1]],
                ['code' => 'B', 'label' => 'Membuat solusi teknologi atau data yang bermanfaat.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Membantu meningkatkan kesehatan dan kehidupan seseorang secara langsung.', 'scores' => ['HHC' => 3, 'PRA' => 1]],
                ['code' => 'D', 'label' => 'Memimpin organisasi atau bisnis yang memberikan dampak.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Membantu menciptakan aturan atau keputusan yang lebih adil.', 'scores' => ['REG' => 3, 'COM' => 1]],
            ],
        ],
        [
            'code' => 'Q42',
            'section' => 'D',
            'title' => 'Lingkungan Kerja',
            'prompt' => 'Tempat kerja mana yang paling mudah kamu bayangkan sebagai tempatmu bekerja?',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Laboratorium atau pusat penelitian.', 'scores' => ['SCI' => 3, 'PRA' => 1]],
                ['code' => 'B', 'label' => 'Klinik atau fasilitas pelayanan kesehatan.', 'scores' => ['PRA' => 3, 'HHC' => 1]],
                ['code' => 'C', 'label' => 'Perusahaan teknologi atau pusat data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'D', 'label' => 'Media, komunikasi atau creative agency.', 'scores' => ['COM' => 3, 'BUS' => 1]],
                ['code' => 'E', 'label' => 'Kantor hukum, lembaga regulasi atau institusi kebijakan.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q43',
            'section' => 'D',
            'title' => 'Proyek Kuliah',
            'prompt' => 'Proyek mana yang paling ingin kamu kerjakan?',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Penelitian mengenai sel atau fenomena biologis.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Membuat aplikasi atau proyek analisis data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'C', 'label' => 'Membuat program pelayanan kesehatan masyarakat.', 'scores' => ['HHC' => 3, 'PRA' => 1]],
                ['code' => 'D', 'label' => 'Membuat event, kampanye, atau proyek bisnis.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Menganalisis sebuah kasus hukum atau kebijakan.', 'scores' => ['REG' => 3, 'COM' => 1]],
            ],
        ],
        [
            'code' => 'Q44',
            'section' => 'D',
            'title' => 'Gambaran Dirimu di Masa Depan',
            'prompt' => 'Kamu paling ingin dikenal sebagai seseorang yang:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Penasaran dan kuat dalam penelitian ilmiah.', 'scores' => ['SCI' => 3, 'ANA' => 1]],
                ['code' => 'B', 'label' => 'Terampil dan dapat diandalkan dalam pelayanan kesehatan.', 'scores' => ['HHC' => 3, 'PRA' => 1]],
                ['code' => 'C', 'label' => 'Pandai menyelesaikan masalah menggunakan teknologi dan data.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'D', 'label' => 'Mampu berkomunikasi dan memengaruhi banyak orang.', 'scores' => ['COM' => 3, 'BUS' => 1]],
                ['code' => 'E', 'label' => 'Kritis, adil dan mampu menilai suatu masalah dari berbagai sisi.', 'scores' => ['REG' => 3, 'ANA' => 1]],
            ],
        ],
        [
            'code' => 'Q45',
            'section' => 'D',
            'title' => 'Hal yang Paling Menarik dari Sebuah Karier',
            'prompt' => 'Yang paling menarik bagimu adalah kesempatan untuk:',
            'type' => 'single_choice',
            'options' => [
                ['code' => 'A', 'label' => 'Menemukan dan mengembangkan pengetahuan baru.', 'scores' => ['SCI' => 3, 'TEC' => 1]],
                ['code' => 'B', 'label' => 'Memberikan pelayanan dan dampak langsung kepada manusia.', 'scores' => ['HHC' => 3, 'PRA' => 1]],
                ['code' => 'C', 'label' => 'Membangun sistem atau teknologi untuk menyelesaikan masalah.', 'scores' => ['TEC' => 3, 'ANA' => 1]],
                ['code' => 'D', 'label' => 'Memimpin organisasi dan mengembangkan bisnis.', 'scores' => ['BUS' => 3, 'COM' => 1]],
                ['code' => 'E', 'label' => 'Menangani argumen, aturan, kebijakan atau hak.', 'scores' => ['REG' => 3, 'COM' => 1]],
            ],
        ],
    ],
    'programs' => [
        'biomedical_science' => [
            'label' => 'Biomedical Science',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.25, 'HHC' => 0.18, 'TEC' => 0.12, 'ANA' => 0.20, 'COM' => 0.05, 'BUS' => 0.03, 'REG' => 0.05, 'PRA' => 0.12],
        ],
        'biotechnology' => [
            'label' => 'Biotechnology',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.28, 'HHC' => 0.07, 'TEC' => 0.20, 'ANA' => 0.20, 'COM' => 0.05, 'BUS' => 0.07, 'REG' => 0.03, 'PRA' => 0.10],
        ],
        'law' => [
            'label' => 'Law',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.03, 'HHC' => 0.03, 'TEC' => 0.04, 'ANA' => 0.22, 'COM' => 0.20, 'BUS' => 0.08, 'REG' => 0.35, 'PRA' => 0.05],
        ],
        'management' => [
            'label' => 'Management',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.03, 'HHC' => 0.03, 'TEC' => 0.10, 'ANA' => 0.15, 'COM' => 0.18, 'BUS' => 0.40, 'REG' => 0.06, 'PRA' => 0.05],
        ],
        'communication_science' => [
            'label' => 'Communication Science',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.02, 'HHC' => 0.05, 'TEC' => 0.12, 'ANA' => 0.10, 'COM' => 0.45, 'BUS' => 0.15, 'REG' => 0.06, 'PRA' => 0.05],
        ],
        'bachelor_midwifery' => [
            'label' => 'Bachelor of Midwifery',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.12, 'HHC' => 0.27, 'TEC' => 0.05, 'ANA' => 0.15, 'COM' => 0.13, 'BUS' => 0.05, 'REG' => 0.06, 'PRA' => 0.17],
        ],
        'diploma_midwifery' => [
            'label' => 'Diploma of Midwifery',
            'recommendation_type' => 'DIRECT_ENTRY',
            'weights' => ['SCI' => 0.08, 'HHC' => 0.30, 'TEC' => 0.03, 'ANA' => 0.08, 'COM' => 0.12, 'BUS' => 0.04, 'REG' => 0.07, 'PRA' => 0.28],
        ],
        'professional_midwifery' => [
            'label' => 'Professional Midwifery pathway',
            'recommendation_type' => 'PROFESSIONAL_PATHWAY',
            'weights' => ['SCI' => 0.08, 'HHC' => 0.28, 'TEC' => 0.03, 'ANA' => 0.14, 'COM' => 0.12, 'BUS' => 0.03, 'REG' => 0.10, 'PRA' => 0.22],
        ],
    ],
    'scoring' => [
        'section_a' => [
            'minimum_item_score' => 1,
            'maximum_item_score' => 5,
            'items_per_dimension' => 3,
            'normalization' => '((dimension_total - minimum_possible_total) / (maximum_possible_total - minimum_possible_total)) * 100',
        ],
        'section_b' => ['primary_score' => 3, 'secondary_score' => 1, 'normalize_against_configured_maximum' => true],
        'section_c' => ['likert_normalized_values' => [1 => 0, 2 => 25, 3 => 50, 4 => 75, 5 => 100]],
        'section_d' => ['primary_score' => 3, 'secondary_score' => 1, 'normalize_against_configured_maximum' => true],
        'final_dimension_formula' => 'A * 0.45 + B * 0.30 + C * 0.15 + D * 0.10',
        'program_formula' => 'sum(final_dimension_score * program_dimension_weight)',
    ],
    'thresholds' => [
        'classifications' => [
            ['minimum' => 85, 'maximum' => 100, 'label' => 'Sangat Kuat'],
            ['minimum' => 75, 'maximum' => 84.99, 'label' => 'Kuat'],
            ['minimum' => 65, 'maximum' => 74.99, 'label' => 'Cukup Kuat'],
            ['minimum' => 55, 'maximum' => 64.99, 'label' => 'Eksploratif'],
            ['minimum' => 0, 'maximum' => 54.99, 'label' => 'Belum Dominan'],
        ],
        'direct_recommendation_minimum' => 55,
        'direct_recommendation_limit' => 3,
        'professional_pathway_minimum' => 70,
        'profile_clarity' => [
            'practically_equal_below' => 1,
            'multidisciplinary_below' => 5,
            'fairly_clear_minimum' => 5,
            'very_clear_minimum' => 10,
        ],
        'response_quality' => [
            'straightlining_same_answers_minimum' => 18,
            'straightlining_section_a_items' => 24,
            'fast_completion_below_seconds' => 240,
            'low_response_consistency_dimensions_minimum' => 4,
            'low_profile_differentiation' => 'calibrate_after_pilot',
        ],
    ],
    'result_text' => [
        'score_name' => 'Indeks Kecocokan Minat',
        'no_dominant_title' => 'Profil Minat Masih Terbuka',
        'no_dominant_body' => 'Belum ada bidang yang mencapai ambang rekomendasi. Gunakan hasil ini untuk mengeksplorasi beberapa pilihan dan berdiskusi dengan orang tua, guru, atau pendamping pendidikan.',
        'multidisciplinary' => 'Dua bidang sama-sama layak dieksplorasi karena skor keduanya berdekatan.',
        'biomedical_biotechnology_overlap' => 'Biomedical Science dan Biotechnology memiliki irisan dalam eksplorasi ilmu hayati. Biomedical Science lebih dekat pada manusia dan kesehatan, sedangkan Biotechnology lebih menekankan pemanfaatan proses biologis dan teknologi.',
        'midwifery_overlap' => 'Bachelor of Midwifery dan Diploma of Midwifery sama-sama berorientasi pada pelayanan kesehatan. Jalur sarjana lebih menonjolkan evidence-based dan analytical orientation, sedangkan jalur diploma lebih menonjolkan praktik langsung yang terstruktur.',
        'professional_pathway' => 'Aspirasi Profesi yang Terdeteksi',
        'professional_pathway_body' => 'Jalur profesi merupakan pendidikan lanjutan dan tidak termasuk peringkat pilihan masuk langsung. Persyaratan akademik yang berlaku tetap harus dipenuhi.',
        'disclaimer' => 'Hasil eksplorasi ini merupakan pemetaan awal terhadap minat belajar dan preferensi aktivitas. Hasil ini bukan diagnosis psikologis ataupun penilaian kemampuan akademik.',
    ],
];
