<?php
declare(strict_types=1);

require __DIR__ . '/_init.php';
adiwira_require_permission($pdo, 'plugin.study-interest.config.view', false);
$versions = $pdo->query("SELECT id,version_code,status,configuration_hash,configuration_json FROM study_interest_test_versions ORDER BY (status='draft') DESC,(status='published') DESC,id DESC")->fetchAll(PDO::FETCH_ASSOC);
$requested = filter_var($_GET['version_id'] ?? null, FILTER_VALIDATE_INT, ['options' => ['min_range' => 1]]);
$version = null;
foreach ($versions as $candidate) if ($requested && (int)$candidate['id'] === (int)$requested) { $version = $candidate; break; }
if ($version === null && $versions !== []) $version = $versions[0];
$configuration = $version !== null ? json_decode((string)$version['configuration_json'], true, 512, JSON_THROW_ON_ERROR) : [];
if ($version !== null && (!is_array($configuration) || !hash_equals((string)$version['configuration_hash'], hash('sha256', study_interest_configuration_json($configuration))))) throw new RuntimeException('Assessment configuration integrity check failed.');
$editable = $version !== null && (string)$version['status'] === 'draft' && study_interest_admin_can('plugin.study-interest.config.manage');
$action = study_interest_admin_action_url('structure/save');
$hidden = static function (array $version, string $operation): void {
    ?><input type="hidden" name="csrf_token" value="<?= study_interest_h(csrf_token()) ?>"><input type="hidden" name="version_id" value="<?= (int)$version['id'] ?>"><input type="hidden" name="expected_hash" value="<?= study_interest_h((string)$version['configuration_hash']) ?>"><input type="hidden" name="operation" value="<?= study_interest_h($operation) ?>"><?php
};
?>
<div class="sie-admin sie-workspace-page">
  <?php study_interest_admin_nav('structure'); ?>
  <header class="sie-admin-head"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Assessment builder')) ?></span><h1 class="page-heading"><?= study_interest_h(__('Structure and study directions')) ?></h1><p><?= study_interest_h(__('Create the sections, dimensions, and directions that define this assessment. Codes remain stable after creation; labels and weights can be changed while the version is a draft.')) ?></p></div><?php if ($version !== null): ?><div class="sie-admin-actions"><a class="adam-button secondary" href="<?= study_interest_h(study_interest_admin_url('questions', ['version_id' => (int)$version['id']])) ?>"><?= study_interest_h(__('Open question bank')) ?></a></div><?php endif; ?></header>
  <section class="sie-filter-bar"><div><span><?= study_interest_h(__('Builder version')) ?></span><strong><?= study_interest_h($version !== null ? ucfirst((string)$version['status']) : __('No version')) ?></strong></div><form method="get" action="<?= study_interest_h(rtrim((string)ADMIN_BASE_PATH, '/') . '/') ?>"><input type="hidden" name="page" value="admin/tools/study-interest/structure"><label><span><?= study_interest_h(__('Assessment version')) ?></span><select class="adam-input" name="version_id" data-sie-autosubmit><?php foreach ($versions as $candidate): ?><option value="<?= (int)$candidate['id'] ?>" <?= $version !== null && (int)$candidate['id'] === (int)$version['id'] ? 'selected' : '' ?>><?= study_interest_h((string)$candidate['version_code'] . ' · ' . ucfirst((string)$candidate['status'])) ?></option><?php endforeach; ?></select></label></form></section>
  <?php if ($version === null): ?><div class="sie-analytics-empty"><h2><?= study_interest_h(__('No assessment yet')) ?></h2><p><?= study_interest_h(__('Create an assessment before defining its structure.')) ?></p></div><?php else: ?>
  <?php if (!$editable): ?><div class="sie-callout"><strong><?= study_interest_h(__('Read-only version')) ?></strong><p><?= study_interest_h(__('Published and retired structures are immutable. Create a draft to make changes.')) ?></p></div><?php endif; ?>

  <section class="sie-admin-section"><div class="sie-admin-section__head"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Step 1')) ?></span><h2><?= study_interest_h(__('Sections')) ?></h2></div><p><?= study_interest_h(__('Sections group questions and control how much each group contributes to dimension scores. Publication requires section weights to total 100%.')) ?></p></div><div class="sie-builder-list">
    <?php foreach ($configuration['sections'] ?? [] as $code => $section): ?><article><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'section_save'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><code><?= study_interest_h((string)$code) ?></code><label><span><?= study_interest_h(__('Label')) ?></span><input class="adam-input" name="label" required maxlength="255" value="<?= study_interest_h((string)$section['label']) ?>" <?= $editable ? '' : 'readonly' ?>></label><label><span><?= study_interest_h(__('Weight')) ?></span><input class="adam-input" type="number" name="weight" min="0" max="1" step="0.00001" required value="<?= study_interest_h((string)$section['weight']) ?>" <?= $editable ? '' : 'readonly' ?>></label><label><span><?= study_interest_h(__('Order')) ?></span><input class="adam-input" type="number" name="display_order" min="1" max="999" required value="<?= (int)($section['display_order'] ?? 1) ?>" <?= $editable ? '' : 'readonly' ?>></label><?php if ($editable): ?><button class="adam-button secondary" type="submit"><?= study_interest_h(__('Save')) ?></button><?php endif; ?></form><?php if ($editable): ?><form method="post" action="<?= study_interest_h($action) ?>" data-sie-confirm><?php $hidden($version, 'section_delete'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><button class="sie-row-action" type="submit"><?= study_interest_h(__('Delete')) ?></button></form><?php endif; ?></article><?php endforeach; ?>
    <?php if ($editable): ?><article class="is-new"><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'section_save'); ?><input class="adam-input" name="code" required maxlength="20" pattern="[A-Za-z0-9][A-Za-z0-9_-]{0,19}" placeholder="SECTION"><input class="adam-input" name="label" required maxlength="255" placeholder="Section label"><input class="adam-input" type="number" name="weight" min="0" max="1" step="0.00001" required value="0"><input class="adam-input" type="number" name="display_order" min="1" max="999" required value="<?= count($configuration['sections'] ?? []) + 1 ?>"><button class="adam-button" type="submit"><?= study_interest_h(__('Add section')) ?></button></form></article><?php endif; ?>
  </div></section>

  <section class="sie-admin-section"><div class="sie-admin-section__head"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Step 2')) ?></span><h2><?= study_interest_h(__('Dimensions')) ?></h2></div><p><?= study_interest_h(__('Dimensions are the traits or interest areas measured by answer scores. A dimension cannot be deleted while questions or directions still reference it.')) ?></p></div><div class="sie-builder-list">
    <?php foreach ($configuration['dimensions'] ?? [] as $code => $dimension): ?><article><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'dimension_save'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><code><?= study_interest_h((string)$code) ?></code><label><span><?= study_interest_h(__('Label')) ?></span><input class="adam-input" name="label" required maxlength="255" value="<?= study_interest_h((string)$dimension['label']) ?>" <?= $editable ? '' : 'readonly' ?>></label><label class="is-grow"><span><?= study_interest_h(__('Description')) ?></span><input class="adam-input" name="description" maxlength="1000" value="<?= study_interest_h((string)($dimension['description'] ?? '')) ?>" <?= $editable ? '' : 'readonly' ?>></label><label><span><?= study_interest_h(__('Order')) ?></span><input class="adam-input" type="number" name="display_order" min="1" max="999" required value="<?= (int)($dimension['display_order'] ?? 1) ?>" <?= $editable ? '' : 'readonly' ?>></label><?php if ($editable): ?><button class="adam-button secondary" type="submit"><?= study_interest_h(__('Save')) ?></button><?php endif; ?></form><?php if ($editable): ?><form method="post" action="<?= study_interest_h($action) ?>" data-sie-confirm><?php $hidden($version, 'dimension_delete'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><button class="sie-row-action" type="submit"><?= study_interest_h(__('Delete')) ?></button></form><?php endif; ?></article><?php endforeach; ?>
    <?php if ($editable): ?><article class="is-new"><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'dimension_save'); ?><input class="adam-input" name="code" required maxlength="20" pattern="[A-Z][A-Z0-9_]{0,19}" placeholder="DIM"><input class="adam-input" name="label" required maxlength="255" placeholder="Dimension label"><input class="adam-input is-grow" name="description" maxlength="1000" placeholder="What this dimension measures"><input class="adam-input" type="number" name="display_order" min="1" max="999" required value="<?= count($configuration['dimensions'] ?? []) + 1 ?>"><button class="adam-button" type="submit"><?= study_interest_h(__('Add dimension')) ?></button></form></article><?php endif; ?>
  </div></section>

  <section class="sie-admin-section"><div class="sie-admin-section__head"><div><span class="sie-admin-eyebrow"><?= study_interest_h(__('Step 3')) ?></span><h2><?= study_interest_h(__('Study directions')) ?></h2></div><p><?= study_interest_h(__('Directions combine dimension scores. Primary directions appear in the ranked result; further pathways appear separately when their threshold is met.')) ?></p></div><div class="sie-direction-builder">
    <?php foreach ($configuration['programs'] ?? [] as $code => $program): ?><article><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'program_save'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><div class="sie-program-editor__head"><code><?= study_interest_h((string)$code) ?></code><label><span><?= study_interest_h(__('Label')) ?></span><input class="adam-input" name="label" required maxlength="255" value="<?= study_interest_h((string)$program['label']) ?>" <?= $editable ? '' : 'readonly' ?>></label><label><span><?= study_interest_h(__('Type')) ?></span><select class="adam-input" name="recommendation_type" <?= $editable ? '' : 'disabled' ?>><option value="DIRECT_ENTRY" <?= (string)$program['recommendation_type'] === 'DIRECT_ENTRY' ? 'selected' : '' ?>><?= study_interest_h(__('Primary direction')) ?></option><option value="PROFESSIONAL_PATHWAY" <?= (string)$program['recommendation_type'] === 'PROFESSIONAL_PATHWAY' ? 'selected' : '' ?>><?= study_interest_h(__('Further pathway')) ?></option></select></label></div><div class="sie-program-weight-grid"><?php foreach ($configuration['dimensions'] ?? [] as $dimensionCode => $dimension): ?><label><span><b><?= study_interest_h((string)$dimensionCode) ?></b><?= study_interest_h((string)$dimension['label']) ?></span><input class="adam-input" type="number" min="0" max="1" step="0.00001" name="weights[<?= study_interest_h((string)$dimensionCode) ?>]" required value="<?= study_interest_h((string)($program['weights'][$dimensionCode] ?? 0)) ?>" <?= $editable ? '' : 'readonly' ?>></label><?php endforeach; ?></div><?php if ($editable): ?><button class="adam-button secondary" type="submit"><?= study_interest_h(__('Save direction')) ?></button><?php endif; ?></form><?php if ($editable): ?><form method="post" action="<?= study_interest_h($action) ?>" data-sie-confirm><?php $hidden($version, 'program_delete'); ?><input type="hidden" name="code" value="<?= study_interest_h((string)$code) ?>"><button class="sie-row-action" type="submit"><?= study_interest_h(__('Delete direction')) ?></button></form><?php endif; ?></article><?php endforeach; ?>
    <?php if ($editable): ?><article class="is-new"><form method="post" action="<?= study_interest_h($action) ?>"><?php $hidden($version, 'program_save'); ?><div class="sie-program-editor__head"><input class="adam-input" name="code" required maxlength="40" pattern="[A-Za-z0-9][A-Za-z0-9_-]{0,39}" placeholder="direction-code"><input class="adam-input" name="label" required maxlength="255" placeholder="Study direction"><select class="adam-input" name="recommendation_type"><option value="DIRECT_ENTRY"><?= study_interest_h(__('Primary direction')) ?></option><option value="PROFESSIONAL_PATHWAY"><?= study_interest_h(__('Further pathway')) ?></option></select></div><div class="sie-program-weight-grid"><?php foreach ($configuration['dimensions'] ?? [] as $dimensionCode => $dimension): ?><label><span><b><?= study_interest_h((string)$dimensionCode) ?></b><?= study_interest_h((string)$dimension['label']) ?></span><input class="adam-input" type="number" min="0" max="1" step="0.00001" name="weights[<?= study_interest_h((string)$dimensionCode) ?>]" required value="0"></label><?php endforeach; ?></div><button class="adam-button" type="submit"><?= study_interest_h(__('Add direction')) ?></button></form></article><?php endif; ?>
  </div></section>
  <?php endif; ?>
</div>
